In [4]:
math = [ [0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14] ]

print (math)
print (math [1])
print (math [1] [3])

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
[5, 6, 7, 8, 9]
8


In [13]:
import math

x = 4 
y = 8 * math.sin (x)
z = y * math.pi
zz = math.sin (y)

print (y)
print (z)
print (zz)

-6.054419962463426
-19.02052127582249
0.22677520771987236


In [16]:
import math

math.degrees (math.pi)
help (math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [42]:
import numpy as np
import pandas as pd

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
print (type (lst))
print (lst)

lst_arr = np.array (lst) ## Casting
print (type (lst_arr))
print (lst_arr)

print ('\nVendita mensile maggiore :', lst_arr.max())
print ('Vendita mensile minore :', lst_arr.min())

lst_filtr = lst_arr >= 4999
print ('\nNumero vendite mensili maggiori di 4999 oggetti :', len (lst_arr [lst_filtr]))
print ('Vendite mensili maggiori di 4999 oggetti :', lst_arr [lst_filtr])

lst_filtr2 = lst_arr <= 3000
print ('\nNumero vendite mensili minori di 3000 oggetti :', len (lst_arr [lst_filtr2]))
print ('Vendite mensili minori di 3000 oggetti :', lst_arr [lst_filtr2])

print ('Media vendite :', lst_arr.mean())

<class 'list'>
[2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
<class 'numpy.ndarray'>
[2000 5500 7200 4320 1280 1900 2500 3900 6410 8150 7100 5350]

Vendita mensile maggiore : 8150
Vendita mensile minore : 1280

Numero vendite mensili maggiori di 4999 oggetti : 6
Vendite mensili maggiori di 4999 oggetti : [5500 7200 6410 8150 7100 5350]

Numero vendite mensili minori di 3000 oggetti : 4
Vendite mensili minori di 3000 oggetti : [2000 1280 1900 2500]
Media vendite : 4634.166666666667


In [46]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))
 ## fatturati_series = pd.Series (fatturati_dict)
print (type (fatturati_dict))
print (fatturati_dict)
print (type (fatturati_series))
print (fatturati_series)

x = fatturati_dict[1997] 
y = fatturati_series[1997]
z = fatturati_dict[2004]
w = fatturati_series[2004]

print (x, y)
print (z, w)

<class 'dict'>
{1997: 12000, 1998: 15000, 1999: 20000, 2000: 23000, 2001: 25000, 2002: 17000, 2003: 14000, 2004: 21000}
<class 'pandas.core.series.Series'>
1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64
12000 12000
21000 21000


In [56]:
import numpy as np 
salaries = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
print (salaries)

salaries_x2 = (salaries *2)
print (salaries_x2)

for salary in salaries:
    agg = salary *2
    print (salaries [salary]) ##? Modo per aggiornare o replaace np.array

print (salaries)

[ 100  200  300  400  500  600  700  800  900 1000]
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


IndexError: index 100 is out of bounds for axis 0 with size 10